service: emission

plugins:
  - serverless-plugin-modularize
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-prune-plugin

package:
  individually: true

custom:
  stage: ${self:provider.stage}
  modularize:
    glob: 'src/**/*.module.yml'

  prune:
    automatic: true
    number: 1

  webpack:
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 1
  memorySize: 1536

