
provider:
  environment:
    REGISTRY_BUCKET: ${self:custom.registry.name}

custom:
  registry:
    name: registry-${self:custom.stage}-bucket

    arn:
      Fn::GetAtt:
        - RegistryBucket
        - Arn

    role:
      Effect: Allow
      Action:
        - 's3:PutObject'
        - 's3:PutObjectAcl'
        - 's3:GetObject'
        - 's3:GetObjectAcl'
        - 's3:DeleteObject'
      Resource:
        - arn:aws:s3:::${self:custom.registry.name}
        - arn:aws:s3:::${self:custom.registry.name}/*

resources:
  Resources: 
    RegistryBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.registry.name}