
provider:
  environment:
    EVENT_TABLE: ${self:custom.ddb.name}


custom:
  ddb:
    name: event-${self:provider.stage}-table

    role:
      Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.ddb.name}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.ddb.name}/*

resources:
  Resources: 
    EventTabel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ddb.name}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: hid
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          -
            IndexName: HashGSI
            KeySchema:
              -
                AttributeName: hid
                KeyType: HASH
            Projection:
              ProjectionType: ALL